services:
  app:
    image: mysociety/voting-2024-change-analysis:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/voting_2024_change_analysis      
    volumes:
      - ./:/workspaces/voting_2024_change_analysis/